spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
        enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: true
      connection-test-query: select 1 from dual;
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 1
      pool-name: movieConnectionPooling
      transaction-isolation: TRANSACTION_READ_COMMITTED
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
    # Mode to apply when determining if DataSource initialization should be performed using the available DDL (schema
    # .sql) and DML (data.sql) scripts.
    initialization-mode: never
    password: sa
    platform: h2
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:~/eshop-app;IFEXISTS=FALSE;AUTO_SERVER=TRUE;
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      # Whether to use Hibernate's newer IdentifierGenerator for AUTO, TABLE and SEQUENCE.
      use-new-id-generator-mappings: true
    # Stops a JPA EntityManager from being bound to the thread for the entire processing of the request
    open-in-view: false
    properties:
      hibernate:
        batch_versioned_data: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 100
        format_sql: true
        order_inserts: true
        order_updates: true
    show-sql: false
  freemarker:
    checkTemplateLocation: false
  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          service-url: http://localhost:8080 # access url for the instance, needed for the SBA server to map properly (optional not required)
management:
  endpoints:
    web:
      exposure:
        include: "*"
